openapi: 3.0.2
info:
  title: 'Recipe-app project'
  version: "0.1"
paths:
  /recipes/:
    get:
      operationId: RecipeListView
      description: 'Recipeslist'
      parameters: []
      responses:
        '200':
          content: ''
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Recipes'
          description: ''
      tags:
        - recipes


  /recipes/{id}/:
    get:
      operationId: RecipeDetailView
      description: 'RecipeDetail'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this news.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recipes'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Recipes'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipes'
          description: ''
      tags:
        - recipe

components:
  schemas:
    Recipes:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
      required:
        - name
        - title