# Generated by Django 5.1.3 on 2024-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipe_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
